name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: cmake
      run: cmake -B build
    - name: make
      run: cmake --build build
    - name: ctest
      run: ctest --test-dir build --output-on-failure
