name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install lapack
      run: sudo apt-get install liblapack-dev
    - name: cmake
      run: cmake -B build
    - name: make
      run: cmake --build build
    - name: test
      run: cmake --build build --target test
